// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuYtjvG8SCWT88zFqQKaNZLHsn4csttBI',
    appId: '1:376759971431:web:ccb8bd57011851bc11aec2',
    messagingSenderId: '376759971431',
    projectId: 'madhan-portfolio',
    authDomain: 'madhan-portfolio.firebaseapp.com',
    storageBucket: 'madhan-portfolio.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBfhBEnNz1hBwldQHsxQu_fr50uf_TrzM',
    appId: '1:376759971431:android:1cdd7e835374107211aec2',
    messagingSenderId: '376759971431',
    projectId: 'madhan-portfolio',
    storageBucket: 'madhan-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsvfdRjrzcCOe-fc93nsweEE8bDxgh-z4',
    appId: '1:376759971431:ios:11a3d87acd74fd3c11aec2',
    messagingSenderId: '376759971431',
    projectId: 'madhan-portfolio',
    storageBucket: 'madhan-portfolio.appspot.com',
    iosClientId: '376759971431-uf0k17tl6iu9vmne2gda2270mf3ua8c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.madhanPortfolio',
  );
}
